package main

// NATS ACL Configuration
//
// Generates a nats-server.conf with per-role subject permissions and
// starts nats-server with that config. Each AMF role gets a distinct
// NATS user with a subject allowlist/denylist that enforces the
// architectural boundaries defined in SPEC.md.
//
// Role permissions summary:
//
//   coordinator  — full access to all subjects including amf.internal.*
//   specialist   — can publish results/progress/claims, subscribe to task.announce
//                  CANNOT touch amf.internal.raw or amf.internal.classified
//   watcher      — can ONLY read amf.internal.raw, write amf.internal.classified
//                  and amf.policy.> for warnings. Nothing else.
//   connector    — can ONLY publish to amf.internal.raw (bridges external systems)
//
// Credentials are read from environment variables with hardcoded defaults.
// Set these in production:
//   AMF_COORD_PASS      coordinator password
//   AMF_SPECIALIST_PASS specialist password
//   AMF_WATCHER_PASS    watcher password
//   AMF_CONNECTOR_PASS  connector password
//
// Workers and beigebox should connect as specialist:
//   NATS URL: nats://specialist:<AMF_SPECIALIST_PASS>@127.0.0.1:4222
//
// The coordinator connects with coordinator credentials (set internally).
// The watcher goroutine opens its own connection with watcher credentials.

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"time"
)

// NATSCreds holds credentials for a single NATS role.
type NATSCreds struct {
	User string
	Pass string
}

// AMFNATSConfig holds all role credentials and the generated config path.
type AMFNATSConfig struct {
	Coordinator NATSCreds
	Specialist  NATSCreds
	Watcher     NATSCreds
	Connector   NATSCreds
	ConfigPath  string
}

// getenv returns the env var or a default. Default is used only for
// local dev — override in production.
func getenv(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// LoadNATSConfig reads credentials from environment, writes a nats-server
// config file to a temp path, and returns the config.
func LoadNATSConfig() (*AMFNATSConfig, error) {
	cfg := &AMFNATSConfig{
		Coordinator: NATSCreds{
			User: "coordinator",
			Pass: getenv("AMF_COORD_PASS", "amf-coord-local"),
		},
		Specialist: NATSCreds{
			User: "specialist",
			Pass: getenv("AMF_SPECIALIST_PASS", "amf-specialist-local"),
		},
		Watcher: NATSCreds{
			User: "watcher",
			Pass: getenv("AMF_WATCHER_PASS", "amf-watcher-local"),
		},
		Connector: NATSCreds{
			User: "connector",
			Pass: getenv("AMF_CONNECTOR_PASS", "amf-connector-local"),
		},
	}

	conf, err := writeNATSConf(cfg)
	if err != nil {
		return nil, err
	}
	cfg.ConfigPath = conf
	return cfg, nil
}

// CoordinatorURL returns a NATS URL with coordinator credentials.
func (c *AMFNATSConfig) CoordinatorURL(base string) string {
	return fmt.Sprintf("nats://%s:%s@127.0.0.1:4222",
		c.Coordinator.User, c.Coordinator.Pass)
}

// SpecialistURL returns a NATS URL for specialist agents (workers, beigebox).
func (c *AMFNATSConfig) SpecialistURL() string {
	return fmt.Sprintf("nats://%s:%s@127.0.0.1:4222",
		c.Specialist.User, c.Specialist.Pass)
}

// WatcherURL returns a NATS URL for watcher goroutines.
func (c *AMFNATSConfig) WatcherURL() string {
	return fmt.Sprintf("nats://%s:%s@127.0.0.1:4222",
		c.Watcher.User, c.Watcher.Pass)
}

// ConnectorURL returns a NATS URL for connector agents.
func (c *AMFNATSConfig) ConnectorURL() string {
	return fmt.Sprintf("nats://%s:%s@127.0.0.1:4222",
		c.Connector.User, c.Connector.Pass)
}

// writeNATSConf generates the nats-server.conf and returns its path.
func writeNATSConf(cfg *AMFNATSConfig) (string, error) {
	dir := os.TempDir()
	path := filepath.Join(dir, "amf-nats.conf")

	content := fmt.Sprintf(`# AMF NATS Server Configuration
# Generated by amf-server — do not edit manually.
# Set AMF_*_PASS environment variables to override default credentials.

port: 4222

authorization {
  users: [
    # coordinator — full mesh access including internal subjects
    {
      user: %q
      password: %q
      permissions: {
        publish:   { allow: [">"] }
        subscribe: { allow: [">"] }
      }
    }

    # specialist — task workers, MCP nodes, beigebox
    # Can claim tasks and publish results.
    # CANNOT read or write amf.internal.raw / amf.internal.classified.
    # CAN use reply subjects for request/response.
    {
      user: %q
      password: %q
      permissions: {
        publish: {
          allow: [
            "amf.task.claim",
            "amf.task.progress",
            "amf.task.blocked",
            "amf.result.>",
            "amf.artifact.>",
            "amf.evidence.>",
            "amf.discovery.agent.heartbeat",
            "amf.internal.reply.>"
          ]
          deny: [
            "amf.internal.raw",
            "amf.internal.classified"
          ]
        }
        subscribe: {
          allow: [
            "amf.task.announce",
            "amf.task.>",
            "amf.result.>",
            "amf.discovery.>",
            "amf.policy.>",
            "amf.internal.reply.>"
          ]
          deny: [
            "amf.internal.raw",
            "amf.internal.classified"
          ]
        }
      }
    }

    # watcher — DMZ boundary goroutine
    # Reads ONE subject (amf.internal.raw), writes ONE subject
    # (amf.internal.classified) plus policy warnings.
    # Denied everything else. Enforces the disposable boundary contract.
    {
      user: %q
      password: %q
      permissions: {
        publish: {
          allow: [
            "amf.internal.classified",
            "amf.policy.warning",
            "amf.policy.deny"
          ]
          deny: [">"]
        }
        subscribe: {
          allow: ["amf.internal.raw"]
          deny: [">"]
        }
      }
    }

    # connector — bridges external systems into the mesh
    # Can ONLY publish to amf.internal.raw (so it passes through the watcher).
    # Cannot subscribe to anything — fire-and-forget ingest only.
    {
      user: %q
      password: %q
      permissions: {
        publish: {
          allow: ["amf.internal.raw"]
          deny: [">"]
        }
        subscribe: {
          deny: [">"]
        }
      }
    }
  ]
}
`,
		cfg.Coordinator.User, cfg.Coordinator.Pass,
		cfg.Specialist.User, cfg.Specialist.Pass,
		cfg.Watcher.User, cfg.Watcher.Pass,
		cfg.Connector.User, cfg.Connector.Pass,
	)

	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return "", fmt.Errorf("nats config: write failed: %w", err)
	}
	return path, nil
}

// startNATSWithACL launches nats-server with the generated config.
// Replaces the original startNATS() in main.go.
func startNATSWithACL(cfg *AMFNATSConfig) *exec.Cmd {
	natsPath, err := exec.LookPath("nats-server")
	if err != nil {
		home, _ := os.UserHomeDir()
		natsPath = home + "/bin/nats-server"
	}

	cmd := exec.Command(natsPath, "-c", cfg.ConfigPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		log.Fatalf("failed to start nats-server: %v", err)
	}
	log.Printf("nats-server started (pid %d) with ACL config %s", cmd.Process.Pid, cfg.ConfigPath)
	time.Sleep(300 * time.Millisecond)
	return cmd
}
